### ISSUE TITLE
Add a README.md for this project

### ISSUE THREAD

**Issue by p-soham11** [p-soham11/miro-board#1]
Mention the technologies used, setup process and a basic description

**Comment by milliyin** [comment]
can you make [miro-board-live.vercel.app](https://miro-board-live.vercel.app/) public, so that I can design the readme.md file.
and assign to me this task.

**Comment by p-soham11** [comment]
Hello @milliyin !

Yes, you can definitely design the README.md file. 
I hope my project is public and and kindly ensure a separate branch is created specifically for addressing this Readme issue.

_Thanks and Regards!_
