### ISSUE TITLE
Pencil mode is not working!!

### ISSUE THREAD

**Issue by venki1402** [p-soham11/miro-board#2]
When you select pencil and try to draw something it automatically goes to select mode.

https://github.com/p-soham11/miro-board/assets/141071215/690f1e71-ca07-4876-9851-6375b6dcf1b7

**Comment by p-soham11** [comment]
Yes Venkatesh! Thank you for pointing this out. 
I am working on this and hope to resolve this on the next update.

_Thanks and Regards._
